image: jangrewe/gitlab-ci-android

variables:
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.2"
  ANDROID_SDK_TOOLS:   "4333796"
  PROJECT_NAME: Treasure_Hunter
  PROJECT_VERSION: 0.0.1

before_script:
  - git remote set-url origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
  - git config --global user.email 'anestis.zioulis@outlook.com'
  - git config --global user.name 'aneziou'
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

stages:
  - build
  - test
  - release

lintDebug:
  stage: build
  only:
    - master
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  only:
    - master
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

debugTests:
  stage: test
  only:
    - master
  script:
    - ./gradlew -Pci --console=plain :app:testDebug
assembleRelease:
  stage: release
  only:
    - master
  script:
    - echo ${KEYSTORE_FILE} | base64 -d > my.keystore
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/my.keystore
      -Pandroid.injected.signing.store.password=${KEYSTORE_PASSWORD}
      -Pandroid.injected.signing.key.alias=${KEY_ALIAS}
      -Pandroid.injected.signing.key.password=${KEY_PASSWORD}
    - mv 'app/build/outputs/apk/release/app-release.apk' 'app/build/outputs/apk/release/${PROJECT_NAME}-${PROJECT_VERSION}-${CI_JOB_ID}.apk'
    - git log --oneline --decorate > CHANGELOG
    - git tag -a ${PROJECT_NAME}-${PROJECT_VERSION}-${CI_JOB_ID} -F CHANGELOG
    - git push origin ${PROJECT_NAME}-${PROJECT_VERSION}-${CI_JOB_ID}
    - |
      curl --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code}\n\n" \
        --data "{\"tag_name\": \"${PROJECT_NAME}-${PROJECT_VERSION}-${CI_JOB_ID}\", \"name\": \"${CI_PROJECT_NAME}-${PROJECT_NAME}-${PROJECT_VERSION}-${CI_JOB_ID}\",  \"assets\": { \"links\": [{ \"name\": \"release\", \"url\": \"https://gitlab.com/aneziou/treasure_hunter_mobile/-/jobs/${CI_JOB_ID}/artifacts/download\" }] }, \"description\": \"No release notes.\"}" \
        --header "Content-Type: application/json" \
        --header "Private-Token: ${TOKEN}" \
        --request POST \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"
  artifacts:
    paths:
      - app/build/outputs/apk/release/${PROJECT_NAME}-${PROJECT_VERSION}-${CI_JOB_ID}.apk
      - CHANGELOG